### ISSUE TITLE
Funds sent over kcc from Kucoin to Coinbase exchange show success but don't reach coinbase exchange as it is not supported, can a feature be added to transfer these back to Kucoin accounts?

### ISSUE THREAD

**Issue by vandanasohrab** [kcc-community/kcc#11]
# Rationale

Why should this feature exist? Lots of users are losing funds
What are the use-cases? A lot of funds are stuck

# Implementation Dont know yet

Do you have ideas regarding the implementation of this feature? No, but willing to explore
Are you willing to implement this feature? Yes

**Comment by viaweb3** [comment]
Only the private key holder can move the funds, thats how blockchain works.

**Comment by vandanasohrab** [comment]
I want to develop a solution and ask coinbase to run it, they dont offer private keys to user of coinbase exchange. Is it okay if we keep this open
