### ISSUE TITLE
I can't make geth

### ISSUE THREAD

**Issue by HosseinTeimouri79** [kcc-community/kcc#117]
root@ubuntu20:~/kcc# make geth

env GO111MODULE=on go run build/ci.go install ./cmd/geth

build github.com/Azure/azure-sdk-for-go/sdk/azcore: cannot load github.com/Azure/azure-sdk-for-go/sdk/azcore: no Go source files
make: *** [Makefile:12: geth] Error 1

**Comment by viaweb3** [comment]
@junnmm

**Comment by junnmm** [comment]
> Azure/azure-sdk-for-go

Sorry, I cannot replicate you error.   
Did you build the latest "kcc" branch?   

Maybe you were using a commit with an incorrect "go.mod" file. Please check your "go.mod" file, it should contain the following line: 

https://github.com/kcc-community/kcc/blob/164ec6c5d45e524706e811e11fd610a6de9b000e/go.mod#L71
