### ISSUE TITLE
I need Gas fee

### ISSUE THREAD

**Issue by HosseinTeimouri79** [kcc-community/kcc#125]
In order to send a transaction on the KCC network, I need to have the gas fee, but no matter how much I search, it is not available anywhere.

**Comment by junnmm** [comment]
> In order to send a transaction on the KCC network, I need to have the gas fee, but no matter how much I search, it is not available anywhere.

We do have a [mainnet faucet ](https://faucet.kcc.io/) where you can request a penny of KCS from. 
And you can purchase more from [Kucoin](https://www.kucoin.com/) and withdraw KCS to KCC network.
