### ISSUE TITLE
Error when building v1.3.2-stable via `make all`

### ISSUE THREAD

**Issue by keennay** [kcc-community/kcc#128]
When attempting to build v1.3.2 using `make all` on an AlmaLinux 8 OS using go1.20.2, the following error is produced:

```
cmd/devp2p/nodesetcmd.go:235:42: undefined: params.SepoliaChainConfig
cmd/devp2p/nodesetcmd.go:235:69: undefined: params.SepoliaGenesisHash
util.go:48: exit status 1
exit status 1
make: *** [Makefile:17: all] Error 1
```

**Comment by junnmm** [comment]
Some tools from go-Ethereum are not supported yet. If you only need the geth binary,  you could build the node only:


make geth

**Comment by keennay** [comment]
> Some tools from go-Ethereum are not supported yet. If you only need the geth binary, you could build the node only: make geth

Thanks yeah that's what I did. Figured I'd give you guys a heads up regardless
