### ISSUE TITLE
1.4.1-stable When executing make geth, the file does not exist. Build github.com/Azure/azure-sdk-for-go/sdk/azcore: cannot load github.com/Azure/azure-sdk-for-go/sdk/ azcore: no Go source files

### ISSUE THREAD

**Issue by zelonH** [kcc-community/kcc#133]
1.4.1-stable When executing make geth, the file does not exist. Build github.com/Azure/azure-sdk-for-go/sdk/azcore: cannot load github.com/Azure/azure-sdk-for-go/sdk/ azcore: no Go source files
![image](https://github.com/kcc-community/kcc/assets/25896081/c784a267-c5ec-4db1-88e0-199004ad70fd)

**Comment by junnmm** [comment]
Hi @hanzhenlong1314 , 

Sorry, we could not replicate your issue.   Looks like your golang compiler does not respect the dependency in the [go.mod](https://github.com/kcc-community/kcc/blob/v1.4.1-stable/go.mod#L71).   

I think this could be a bug in your golang compiler. A similar issue can be found [here](https://github.com/grafana/grafana/issues/41201#issuecomment-1001246245).   

Have you tried "golang 1.18"? That is the version that we [use](https://github.com/kcc-community/kcc/blob/27ea3ffc4072306636c6819a4db0862baedc9784/Dockerfile#L7) for building our [official docker image](https://hub.docker.com/r/kucoincommunitychain/kcc/tags).

**Comment by sarthak1dev** [comment]
hey guys, a newbie here, i want to query this blockchain for specific transactions on chain. can anyone guide me please?

**Comment by junnmm** [comment]
> hey guys, a newbie here, i want to query this blockchain for specific transactions on chain. can anyone guide me please?

You can find more from [our documentation](https://docs.kcc.io/developers/network-endpoints).  If you are familiar with Ethereum, BSC or other EVM chains, your knowledges on those chains will mostly work for KCC.

**Comment by sarthak1dev** [comment]
One doubt
ku coin exchange trades swaps right, but they aren't seen on the back or
eth chains I assume these happen on the kcc???
