### ISSUE TITLE
Pending Tx Stream broken Over IPC using Rust

### ISSUE THREAD

**Issue by j-dbooth** [kcc-community/kcc#134]
#### System information

Geth version: `v1.4.1-stable` (latest)
OS & Version: Windows 10

#### Expected behaviour
subscribes to a new stream of pending tx's

#### Actual behaviour
```
Error: JsonRpcClientError(JsonRpcError(JsonRpcError { code: -32602, message: "too many arguments, want at most 1", data: None }))
error: process didn't exit successfully: `target\debug\revm-playground-bz.exe` (exit code: 1)
```

#### Steps to reproduce the behaviour
```
use ethers::prelude::*;
use ethers::providers::{Provider, Ipc, Middleware};
use std::error::Error;

const IPCPATH: &str = "\\\\.\\pipe\\geth.ipc"; 

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let ipc_provider: Provider<Ipc> = Provider::connect_ipc(IPCPATH).await.unwrap();


    let mut transactions: ethers::providers::SubscriptionStream<'_, Ipc, ethers::types::Transaction> = ipc_provider.subscribe_full_pending_txs().await.unwrap();
    while let Some(tx) = transactions.next().await {
        println!("--------------------------------------------------------------------------------------------------------------------------");
        println!("Tx Hash: {:?}", tx.hash);

        
    }   
    Ok(())
}

**Comment by junnmm** [comment]
Hi,

Looks like this is the backtrace of your own rust program, and it does not include your JSON RPC request payload.

 "The too many arguments error" indicates that you have provided more than one arguments when calling the eth_subscribe method.


See https://geth.ethereum.org/docs/interacting-with-geth/rpc/pubsub for more.

**Comment by junnmm** [comment]
Hi, @j-dbooth   

After digging a little bit into the ethers-rs  codes, I found the root reason for your issue:  

> The "NewPendingTransactions" method in KCC does not support returning full TX body yet.  


## Detailed Explanation 

[The go-ethereum supports this by adding an optional `fullTx` to the `NewPendingTransactions` method](https://github.com/ethereum/go-ethereum/blob/73697529994e14996b7740730481e926d5ec3e40/eth/filters/api.go#L141): 

```golang
func (api *FilterAPI) NewPendingTransactions(ctx context.Context, fullTx *bool) (*rpc.Subscription, error) {
```

But in KCC there is no such `fullTx` in our `NewPendingTransactions` method: 

https://github.com/kcc-community/kcc/blob/27ea3ffc4072306636c6819a4db0862baedc9784/eth/filters/api.go#L137


## The advices from the KCC Team 

1.  Use the [subscribe_pending_txs](https://docs.rs/ethers/latest/ethers/providers/struct.Provider.html#method.subscribe_pending_txs) instead. However, you can only get the hashes first, then you can manually request the body. 
2.  It is safe to replace the  `eth/filters/api.go` file from KCC with the latest one from the `go-ethereum`. And it should work well.  However, you need to build the KCC node from the source. Hope you are familiar with it.
