### ISSUE TITLE
How to fetch token list of selected wallet address?

### ISSUE THREAD

**Issue by topcoder1208** [kcc-community/kcc#15]
I checked all document.

https://documenter.getpostman.com/view/20873420/UyxohiZs
https://docs.kcc.io/#/en-us/
https://scan.kcc.io/graphiql
https://scan.kcc.io/api-docs

There was not any solution for this.
Tried to use moralis. But moralis is not working with kcc network.
what is solution?

**Comment by lingyun92** [comment]
https://documenter.getpostman.com/view/20873420/UyxohiZs#29cd7fe7-c02d-4e8e-af6c-029b35f21e38
