### ISSUE TITLE
I deploy the node through docker, and when it reaches a certain height(2509228), the node cannot be synchronized, please help

### ISSUE THREAD

**Issue by zelonH** [kcc-community/kcc#19]
#### System information

Geth version: `geth version`
Geth
Version: 1.0.5-stable
Git Commit: 0886aaad00c6969b436f5fa14a3138019bf6cab5
Architecture: amd64
Go Version: go1.13.8
Operating System: linux
GOPATH=
GOROOT=go

OS & Version:Linux
Commit hash : v1.0.5

#### Backtrace

[06-19|11:57:51.411] Downloader queue stats                   receiptTasks=0 blockTasks=65    itemSize=1.01KiB  throttle=8192
INFO [06-19|11:57:51.412] Skip duplicated bad block                number=2509228 hash="e164a7…d137e7"
ERROR[06-19|11:57:51.412] 
########## BAD BLOCK #########
Chain config: {ChainID: 321 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Berlin: 0, YOLO v3: <nil>, Engine: posa}

Number: 2509228
Hash: 0xe164a7e1c9d5301ba4757657da9e69453b0d2621cb47250f04c093160cd137e7
         0: cumulative: 144061 gas: 144061 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xee187652c539c4ed94baa053cfc0be7e0f826c663f31a2f52324a27e4d03c3c1 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: 
         1: cumulative: 210394 gas: 66333 contract: 0xbbc06930c6296bf12Ef40E9BB4c519D9d8Ca9084 status: 1 tx: 0xe42c11a8a31f3c0a990a8264b23bf4e936b9d97f3242cfbc21e63b2b0abd09f0 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: 

Error: invalid merkle root (remote: 7aacf3a296614e10d528e544072bc12580ed456d3d307c0e585d9ef5904a2d70 local: 5bdf3322b26b136c888a0a170ddca784bb344112208e4637ac62741f2ee55eed)
##############################
 
WARN [06-19|11:57:51.412] Synchronisation failed, dropping peer    peer=5274a03e6d468a811021d186b7cca561ae3595b91586254aa7c8b0f0f1fa8347 err="retrieved hash chain is invalid: invalid merkle root (remote: 7aacf3a296614e10d528e544072bc12580ed456d3d307c0e585d9ef5904a2d70 local: 5bdf3322b26b136c888a0a170ddca784bb344112208e4637ac62741f2ee55eed)"
ERROR[06-19|11:57:51.412] Ethereum peer removal failed             peer=5274a03e err="peer not registered"
INFO [06-19|11:58:00.006] Looking for peers                        peercount=1 tried=95  static=0
ERROR[06-19|11:58:07.284] Snapshot extension registration failed   peer=3ce52055 err="peer connected on snap without compatible eth support"
INFO [06-19|11:58:10.007] Looking for peers                        peercount=1 tried=184 static=0
ERROR[06-19|11:58:15.332] Snapshot extension registration failed   peer=af5dfeb7 err="peer connected on snap without compatible eth support"
INFO [06-19|11:58:20.042] Looking for peers                        peercount=1 tried=104 static=0
ERROR[06-19|11:58:22.022] Snapshot extension registration failed   peer=cb5b9771 err="peer connected on snap without compatible eth support"
ERROR[06-19|11:58:22.264] Snapshot extension registration failed   peer=cbd3f861 err="peer connected on snap without compatible eth support"
INFO [06-19|11:58:30.064] Looking for peers                        peercount=0 tried=107 static=0
ERROR[06-19|11:58:38.265] Snapshot extension registration failed   peer=33f03161 err="peer connected on snap without compatible eth support"
INFO [06-19|11:58:50.157] Looking for peers                        peercount=0 tried=101 static=0
INFO [06-19|11:59:10.179] Looking for peers                        peercount=0 tried=65  static=0
INFO [06-19|11:59:20.432] Looking for peers                        peercount=0 tried=143 static=0
ERROR[06-19|11:59:25.334] Snapshot extension registration failed   peer=88f932f1 err="peer connected on snap without compatible eth support"
INFO [06-19|11:59:30.469] Looking for peers                        peercount=0 tried=127 static=0
INFO [06-19|11:59:40.527] Looking for peers                        peercount=0 tried=105 static=0
ERROR[06-19|11:59:40.862] Snapshot extension registration failed   peer=7bcee16b err="peer connected on snap without compatible eth support"
ERROR[06-19|11:59:48.787] Snapshot extension registration failed   peer=c2340321 err="peer connected on snap without compatible eth support"
INFO [06-19|11:59:50.577] Looking for peers                        peercount=0 tried=211 static=0

[backtrace]
I deploy the node through docker, and when it reaches a certain height(2509228), the node cannot be synchronized, please help

**Comment by junnmm** [comment]
Hi, sorry for your inconvenience. 

This issue was first reported in #9, and we have already fixed it in recent releases. 
Please upgrade your node version to [v1.2.0](https://github.com/kcc-community/kcc/releases/tag/v1.2.0). 

You can also find the official auto-build docker image from [dockerhub](https://hub.docker.com/r/kucoincommunitychain/kcc/tags).

**Comment by zelonH** [comment]
OK, thanks
