### ISSUE TITLE
debe ser el internet que no funciona tomare mi precaucion 

### ISSUE THREAD

**Issue by Johnangel7** [kcc-community/kcc#26]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by Mongkol67** [comment]
> #### System information
> 
> Geth version: `geth version`
> OS & Version: Windows/Linux/OSX
> Commit hash : (if `develop`)
> 
> #### Expected behaviour
> 
> 
> #### Actual behaviour
> 
> 
> #### Steps to reproduce the behaviour
> 
> 
> #### Backtrace
> 
> ````
> [backtrace]
> ````
>

**Comment by Mongkol67** [comment]
> #### System information
> 
> Geth version: `geth version`
> OS & Version: Windows/Linux/OSX
> Commit hash : (if `develop`)
> 
> #### Expected behaviour
> 
> 
> #### Actual behaviour
> 
> 
> #### Steps to reproduce the behaviour
> 
> 
> #### Backtrace
> 
> ````
> [backtrace]
> ````
>
